package com.tykon.api.framework.service.core.util;

import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.ObjectMapper;

public class CountryData {

	private static Map<String, Country> countryCodeCountryMap = new HashMap<>();
	private static Map<String, Country> countryNameCountryMap = new HashMap<>();
	private static Map<String, Country> countryDialCodeCountryMap = new HashMap<>();

	static {
		try {
			init();
		} catch (IOException e) {
			e.printStackTrace();
		}
	}

	public static void init() throws JsonParseException, JsonMappingException, IOException {
		ObjectMapper mapper = new ObjectMapper();
		String countryJson = "[{\"name\":\"Afghanistan\",\"dialCode\":\"93\",\"code\":\"AF\"},\n"
				+ "{\"name\":\"Albania\",\"dialCode\":\"355\",\"code\":\"AL\"},\n"
				+ "{\"name\":\"Algeria\",\"dialCode\":\"213\",\"code\":\"DZ\"},\n"
				+ "{\"name\":\"American Samoa\",\"dialCode\":\"1\",\"code\":\"AS\"},\n"
				+ "{\"name\":\"Andorra\",\"dialCode\":\"376\",\"code\":\"AD\"},\n"
				+ "{\"name\":\"Angola\",\"dialCode\":\"244\",\"code\":\"AO\"},\n"
				+ "{\"name\":\"Anguilla\",\"dialCode\":\"1\",\"code\":\"AI\"},\n"
				+ "{\"name\":\"Antigua\",\"dialCode\":\"1\",\"code\":\"AG\"},\n"
				+ "{\"name\":\"Argentina\",\"dialCode\":\"54\",\"code\":\"AR\"},\n"
				+ "{\"name\":\"Armenia\",\"dialCode\":\"374\",\"code\":\"AM\"},\n"
				+ "{\"name\":\"Aruba\",\"dialCode\":\"297\",\"code\":\"AW\"},\n"
				+ "{\"name\":\"Australia\",\"dialCode\":\"61\",\"code\":\"AU\"},\n"
				+ "{\"name\":\"Austria\",\"dialCode\":\"43\",\"code\":\"AT\"},\n"
				+ "{\"name\":\"Azerbaijan\",\"dialCode\":\"994\",\"code\":\"AZ\"},\n"
				+ "{\"name\":\"Bahrain\",\"dialCode\":\"973\",\"code\":\"BH\"},\n"
				+ "{\"name\":\"Bangladesh\",\"dialCode\":\"880\",\"code\":\"BD\"},\n"
				+ "{\"name\":\"Barbados\",\"dialCode\":\"1\",\"code\":\"BB\"},\n"
				+ "{\"name\":\"Belarus\",\"dialCode\":\"375\",\"code\":\"BY\"},\n"
				+ "{\"name\":\"Belgium\",\"dialCode\":\"32\",\"code\":\"BE\"},\n"
				+ "{\"name\":\"Belize\",\"dialCode\":\"501\",\"code\":\"BZ\"},\n"
				+ "{\"name\":\"Benin\",\"dialCode\":\"229\",\"code\":\"BJ\"},\n"
				+ "{\"name\":\"Bermuda\",\"dialCode\":\"1\",\"code\":\"BM\"},\n"
				+ "{\"name\":\"Bhutan\",\"dialCode\":\"975\",\"code\":\"BT\"},\n"
				+ "{\"name\":\"Bolivia\",\"dialCode\":\"591\",\"code\":\"BO\"},\n"
				+ "{\"name\":\"Bonaire, Sint Eustatius and Saba\",\"dialCode\":\"599\",\"code\":\"BQ\"},\n"
				+ "{\"name\":\"Bosnia and Herzegovina\",\"dialCode\":\"387\",\"code\":\"BA\"},\n"
				+ "{\"name\":\"Botswana\",\"dialCode\":\"267\",\"code\":\"BW\"},\n"
				+ "{\"name\":\"Brazil\",\"dialCode\":\"55\",\"code\":\"BR\"},\n"
				+ "{\"name\":\"British Indian Ocean Territory\",\"dialCode\":\"246\",\"code\":\"IO\"},\n"
				+ "{\"name\":\"British Virgin Islands\",\"dialCode\":\"1\",\"code\":\"VG\"},\n"
				+ "{\"name\":\"Brunei\",\"dialCode\":\"673\",\"code\":\"BN\"},\n"
				+ "{\"name\":\"Bulgaria\",\"dialCode\":\"359\",\"code\":\"BG\"},\n"
				+ "{\"name\":\"Burkina Faso\",\"dialCode\":\"226\",\"code\":\"BF\"},\n"
				+ "{\"name\":\"Burundi\",\"dialCode\":\"257\",\"code\":\"BI\"},\n"
				+ "{\"name\":\"Cambodia\",\"dialCode\":\"855\",\"code\":\"KH\"},\n"
				+ "{\"name\":\"Cameroon\",\"dialCode\":\"237\",\"code\":\"CM\"},\n"
				+ "{\"name\":\"Canada\",\"dialCode\":\"1\",\"code\":\"CA\"},\n"
				+ "{\"name\":\"Cape Verde\",\"dialCode\":\"238\",\"code\":\"CV\"},\n"
				+ "{\"name\":\"Cayman Islands\",\"dialCode\":\"1\",\"code\":\"KY\"},\n"
				+ "{\"name\":\"Central African Republic\",\"dialCode\":\"236\",\"code\":\"CF\"},\n"
				+ "{\"name\":\"Chad\",\"dialCode\":\"235\",\"code\":\"TD\"},\n"
				+ "{\"name\":\"Chile\",\"dialCode\":\"56\",\"code\":\"CL\"},\n"
				+ "{\"name\":\"China\",\"dialCode\":\"86\",\"code\":\"CN\"},\n"
				+ "{\"name\":\"Colombia\",\"dialCode\":\"57\",\"code\":\"CO\"},\n"
				+ "{\"name\":\"Comoros\",\"dialCode\":\"269\",\"code\":\"KM\"},\n"
				+ "{\"name\":\"Cook Islands\",\"dialCode\":\"682\",\"code\":\"CK\"},\n"
				+ "{\"name\":\"Costa Rica\",\"dialCode\":\"506\",\"code\":\"CR\"},\n"
				+ "{\"name\":\"Côte d'Ivoire\",\"dialCode\":\"225\",\"code\":\"CI\"},\n"
				+ "{\"name\":\"Croatia\",\"dialCode\":\"385\",\"code\":\"HR\"},\n"
				+ "{\"name\":\"Cuba\",\"dialCode\":\"53\",\"code\":\"CU\"},\n"
				+ "{\"name\":\"Curaçao\",\"dialCode\":\"599\",\"code\":\"CW\"},\n"
				+ "{\"name\":\"Cyprus\",\"dialCode\":\"357\",\"code\":\"CY\"},\n"
				+ "{\"name\":\"Czech Republic\",\"dialCode\":\"420\",\"code\":\"CZ\"},\n"
				+ "{\"name\":\"Democratic Republic of the Congo\",\"dialCode\":\"243\",\"code\":\"CD\"},\n"
				+ "{\"name\":\"Denmark\",\"dialCode\":\"45\",\"code\":\"DK\"},\n"
				+ "{\"name\":\"Djibouti\",\"dialCode\":\"253\",\"code\":\"DJ\"},\n"
				+ "{\"name\":\"Dominica\",\"dialCode\":\"1\",\"code\":\"DM\"},\n"
				+ "{\"name\":\"Dominican Republic\",\"dialCode\":\"1\",\"code\":\"DO\"},\n"
				+ "{\"name\":\"Ecuador\",\"dialCode\":\"593\",\"code\":\"EC\"},\n"
				+ "{\"name\":\"Egypt\",\"dialCode\":\"20\",\"code\":\"EG\"},\n"
				+ "{\"name\":\"El Salvador\",\"dialCode\":\"503\",\"code\":\"SV\"},\n"
				+ "{\"name\":\"Equatorial Guinea\",\"dialCode\":\"240\",\"code\":\"GQ\"},\n"
				+ "{\"name\":\"Eritrea\",\"dialCode\":\"291\",\"code\":\"ER\"},\n"
				+ "{\"name\":\"Estonia\",\"dialCode\":\"372\",\"code\":\"EE\"},\n"
				+ "{\"name\":\"Ethiopia\",\"dialCode\":\"251\",\"code\":\"ET\"},\n"
				+ "{\"name\":\"Falkland Islands\",\"dialCode\":\"500\",\"code\":\"FK\"},\n"
				+ "{\"name\":\"Faroe Islands\",\"dialCode\":\"298\",\"code\":\"FO\"},\n"
				+ "{\"name\":\"Federated States of Micronesia\",\"dialCode\":\"691\",\"code\":\"FM\"},\n"
				+ "{\"name\":\"Fiji\",\"dialCode\":\"679\",\"code\":\"FJ\"},\n"
				+ "{\"name\":\"Finland\",\"dialCode\":\"358\",\"code\":\"FI\"},\n"
				+ "{\"name\":\"France\",\"dialCode\":\"33\",\"code\":\"FR\"},\n"
				+ "{\"name\":\"French Guiana\",\"dialCode\":\"594\",\"code\":\"GF\"},\n"
				+ "{\"name\":\"French Polynesia\",\"dialCode\":\"689\",\"code\":\"PF\"},\n"
				+ "{\"name\":\"Gabon\",\"dialCode\":\"241\",\"code\":\"GA\"},\n"
				+ "{\"name\":\"Georgia\",\"dialCode\":\"995\",\"code\":\"GE\"},\n"
				+ "{\"name\":\"Germany\",\"dialCode\":\"49\",\"code\":\"DE\"},\n"
				+ "{\"name\":\"Ghana\",\"dialCode\":\"233\",\"code\":\"GH\"},\n"
				+ "{\"name\":\"Gibraltar\",\"dialCode\":\"350\",\"code\":\"GI\"},\n"
				+ "{\"name\":\"Greece\",\"dialCode\":\"30\",\"code\":\"GR\"},\n"
				+ "{\"name\":\"Greenland\",\"dialCode\":\"299\",\"code\":\"GL\"},\n"
				+ "{\"name\":\"Grenada\",\"dialCode\":\"1\",\"code\":\"GD\"},\n"
				+ "{\"name\":\"Guadeloupe\",\"dialCode\":\"590\",\"code\":\"GP\"},\n"
				+ "{\"name\":\"Guam\",\"dialCode\":\"1\",\"code\":\"GU\"},\n"
				+ "{\"name\":\"Guatemala\",\"dialCode\":\"502\",\"code\":\"GT\"},\n"
				+ "{\"name\":\"Guernsey\",\"dialCode\":\"44\",\"code\":\"GG\"},\n"
				+ "{\"name\":\"Guinea\",\"dialCode\":\"224\",\"code\":\"GN\"},\n"
				+ "{\"name\":\"Guinea-Bissau\",\"dialCode\":\"245\",\"code\":\"GW\"},\n"
				+ "{\"name\":\"Guyana\",\"dialCode\":\"592\",\"code\":\"GY\"},\n"
				+ "{\"name\":\"Haiti\",\"dialCode\":\"509\",\"code\":\"HT\"},\n"
				+ "{\"name\":\"Honduras\",\"dialCode\":\"504\",\"code\":\"HN\"},\n"
				+ "{\"name\":\"Hong Kong\",\"dialCode\":\"852\",\"code\":\"HK\"},\n"
				+ "{\"name\":\"Hungary\",\"dialCode\":\"36\",\"code\":\"HU\"},\n"
				+ "{\"name\":\"Iceland\",\"dialCode\":\"354\",\"code\":\"IS\"},\n"
				+ "{\"name\":\"India\",\"dialCode\":\"91\",\"code\":\"IN\"},\n"
				+ "{\"name\":\"Indonesia\",\"dialCode\":\"62\",\"code\":\"ID\"},\n"
				+ "{\"name\":\"Iran\",\"dialCode\":\"98\",\"code\":\"IR\"},\n"
				+ "{\"name\":\"Iraq\",\"dialCode\":\"964\",\"code\":\"IQ\"},\n"
				+ "{\"name\":\"Ireland\",\"dialCode\":\"353\",\"code\":\"IE\"},\n"
				+ "{\"name\":\"Isle Of Man\",\"dialCode\":\"44\",\"code\":\"IM\"},\n"
				+ "{\"name\":\"Israel\",\"dialCode\":\"972\",\"code\":\"IL\"},\n"
				+ "{\"name\":\"Italy\",\"dialCode\":\"39\",\"code\":\"IT\"},\n"
				+ "{\"name\":\"Jamaica\",\"dialCode\":\"1\",\"code\":\"JM\"},\n"
				+ "{\"name\":\"Japan\",\"dialCode\":\"81\",\"code\":\"JP\"},\n"
				+ "{\"name\":\"Jersey\",\"dialCode\":\"44\",\"code\":\"JE\"},\n"
				+ "{\"name\":\"Jordan\",\"dialCode\":\"962\",\"code\":\"JO\"},\n"
				+ "{\"name\":\"Kazakhstan\",\"dialCode\":\"7\",\"code\":\"KZ\"},\n"
				+ "{\"name\":\"Kenya\",\"dialCode\":\"254\",\"code\":\"KE\"},\n"
				+ "{\"name\":\"Kiribati\",\"dialCode\":\"686\",\"code\":\"KI\"},\n"
				+ "{\"name\":\"Kuwait\",\"dialCode\":\"965\",\"code\":\"KW\"},\n"
				+ "{\"name\":\"Kyrgyzstan\",\"dialCode\":\"996\",\"code\":\"KG\"},\n"
				+ "{\"name\":\"Laos\",\"dialCode\":\"856\",\"code\":\"LA\"},\n"
				+ "{\"name\":\"Latvia\",\"dialCode\":\"371\",\"code\":\"LV\"},\n"
				+ "{\"name\":\"Lebanon\",\"dialCode\":\"961\",\"code\":\"LB\"},\n"
				+ "{\"name\":\"Lesotho\",\"dialCode\":\"266\",\"code\":\"LS\"},\n"
				+ "{\"name\":\"Liberia\",\"dialCode\":\"231\",\"code\":\"LR\"},\n"
				+ "{\"name\":\"Libya\",\"dialCode\":\"218\",\"code\":\"LY\"},\n"
				+ "{\"name\":\"Liechtenstein\",\"dialCode\":\"423\",\"code\":\"LI\"},\n"
				+ "{\"name\":\"Lithuania\",\"dialCode\":\"370\",\"code\":\"LT\"},\n"
				+ "{\"name\":\"Luxembourg\",\"dialCode\":\"352\",\"code\":\"LU\"},\n"
				+ "{\"name\":\"Macau\",\"dialCode\":\"853\",\"code\":\"MO\"},\n"
				+ "{\"name\":\"Macedonia\",\"dialCode\":\"389\",\"code\":\"MK\"},\n"
				+ "{\"name\":\"Madagascar\",\"dialCode\":\"261\",\"code\":\"MG\"},\n"
				+ "{\"name\":\"Malawi\",\"dialCode\":\"265\",\"code\":\"MW\"},\n"
				+ "{\"name\":\"Malaysia\",\"dialCode\":\"60\",\"code\":\"MY\"},\n"
				+ "{\"name\":\"Maldives\",\"dialCode\":\"960\",\"code\":\"MV\"},\n"
				+ "{\"name\":\"Mali\",\"dialCode\":\"223\",\"code\":\"ML\"},\n"
				+ "{\"name\":\"Malta\",\"dialCode\":\"356\",\"code\":\"MT\"},\n"
				+ "{\"name\":\"Marshall Islands\",\"dialCode\":\"692\",\"code\":\"MH\"},\n"
				+ "{\"name\":\"Martinique\",\"dialCode\":\"596\",\"code\":\"MQ\"},\n"
				+ "{\"name\":\"Mauritania\",\"dialCode\":\"222\",\"code\":\"MR\"},\n"
				+ "{\"name\":\"Mauritius\",\"dialCode\":\"230\",\"code\":\"MU\"},\n"
				+ "{\"name\":\"Mayotte\",\"dialCode\":\"262\",\"code\":\"YT\"},\n"
				+ "{\"name\":\"Mexico\",\"dialCode\":\"52\",\"code\":\"MX\"},\n"
				+ "{\"name\":\"Moldova\",\"dialCode\":\"373\",\"code\":\"MD\"},\n"
				+ "{\"name\":\"Monaco\",\"dialCode\":\"377\",\"code\":\"MC\"},\n"
				+ "{\"name\":\"Mongolia\",\"dialCode\":\"976\",\"code\":\"MN\"},\n"
				+ "{\"name\":\"Montenegro\",\"dialCode\":\"382\",\"code\":\"ME\"},\n"
				+ "{\"name\":\"Montserrat\",\"dialCode\":\"1\",\"code\":\"MS\"},\n"
				+ "{\"name\":\"Morocco\",\"dialCode\":\"212\",\"code\":\"MA\"},\n"
				+ "{\"name\":\"Mozambique\",\"dialCode\":\"258\",\"code\":\"MZ\"},\n"
				+ "{\"name\":\"Myanmar\",\"dialCode\":\"95\",\"code\":\"MM\"},\n"
				+ "{\"name\":\"Namibia\",\"dialCode\":\"264\",\"code\":\"NA\"},\n"
				+ "{\"name\":\"Nauru\",\"dialCode\":\"674\",\"code\":\"NR\"},\n"
				+ "{\"name\":\"Nepal\",\"dialCode\":\"977\",\"code\":\"NP\"},\n"
				+ "{\"name\":\"Netherlands\",\"dialCode\":\"31\",\"code\":\"NL\"},\n"
				+ "{\"name\":\"New Caledonia\",\"dialCode\":\"687\",\"code\":\"NC\"},\n"
				+ "{\"name\":\"New Zealand\",\"dialCode\":\"64\",\"code\":\"NZ\"},\n"
				+ "{\"name\":\"Nicaragua\",\"dialCode\":\"505\",\"code\":\"NI\"},\n"
				+ "{\"name\":\"Niger\",\"dialCode\":\"227\",\"code\":\"NE\"},\n"
				+ "{\"name\":\"Nigeria\",\"dialCode\":\"234\",\"code\":\"NG\"},\n"
				+ "{\"name\":\"Niue\",\"dialCode\":\"683\",\"code\":\"NU\"},\n"
				+ "{\"name\":\"Norfolk Island\",\"dialCode\":\"672\",\"code\":\"NF\"},\n"
				+ "{\"name\":\"North Korea\",\"dialCode\":\"850\",\"code\":\"KP\"},\n"
				+ "{\"name\":\"Northern Mariana Islands\",\"dialCode\":\"1\",\"code\":\"MP\"},\n"
				+ "{\"name\":\"Norway\",\"dialCode\":\"47\",\"code\":\"NO\"},\n"
				+ "{\"name\":\"Oman\",\"dialCode\":\"968\",\"code\":\"OM\"},\n"
				+ "{\"name\":\"Pakistan\",\"dialCode\":\"92\",\"code\":\"PK\"},\n"
				+ "{\"name\":\"Palau\",\"dialCode\":\"680\",\"code\":\"PW\"},\n"
				+ "{\"name\":\"Palestine\",\"dialCode\":\"970\",\"code\":\"PS\"},\n"
				+ "{\"name\":\"Panama\",\"dialCode\":\"507\",\"code\":\"PA\"},\n"
				+ "{\"name\":\"Papua New Guinea\",\"dialCode\":\"675\",\"code\":\"PG\"},\n"
				+ "{\"name\":\"Paraguay\",\"dialCode\":\"595\",\"code\":\"PY\"},\n"
				+ "{\"name\":\"Peru\",\"dialCode\":\"51\",\"code\":\"PE\"},\n"
				+ "{\"name\":\"Philippines\",\"dialCode\":\"63\",\"code\":\"PH\"},\n"
				+ "{\"name\":\"Poland\",\"dialCode\":\"48\",\"code\":\"PL\"},\n"
				+ "{\"name\":\"Portugal\",\"dialCode\":\"351\",\"code\":\"PT\"},\n"
				+ "{\"name\":\"Puerto Rico\",\"dialCode\":\"1\",\"code\":\"PR\"},\n"
				+ "{\"name\":\"Qatar\",\"dialCode\":\"974\",\"code\":\"QA\"},\n"
				+ "{\"name\":\"Republic of the Congo\",\"dialCode\":\"242\",\"code\":\"CG\"},\n"
				+ "{\"name\":\"Réunion\",\"dialCode\":\"262\",\"code\":\"RE\"},\n"
				+ "{\"name\":\"Romania\",\"dialCode\":\"40\",\"code\":\"RO\"},\n"
				+ "{\"name\":\"Russia\",\"dialCode\":\"7\",\"code\":\"RU\"},\n"
				+ "{\"name\":\"Rwanda\",\"dialCode\":\"250\",\"code\":\"RW\"},\n"
				+ "{\"name\":\"Saint Helena\",\"dialCode\":\"290\",\"code\":\"SH\"},\n"
				+ "{\"name\":\"Saint Kitts and Nevis\",\"dialCode\":\"1\",\"code\":\"KN\"},\n"
				+ "{\"name\":\"Saint Pierre and Miquelon\",\"dialCode\":\"508\",\"code\":\"PM\"},\n"
				+ "{\"name\":\"Saint Vincent and the Grenadines\",\"dialCode\":\"1\",\"code\":\"VC\"},\n"
				+ "{\"name\":\"Samoa\",\"dialCode\":\"685\",\"code\":\"WS\"},\n"
				+ "{\"name\":\"San Marino\",\"dialCode\":\"378\",\"code\":\"SM\"},\n"
				+ "{\"name\":\"Sao Tome and Principe\",\"dialCode\":\"239\",\"code\":\"ST\"},\n"
				+ "{\"name\":\"Saudi Arabia\",\"dialCode\":\"966\",\"code\":\"SA\"},\n"
				+ "{\"name\":\"Senegal\",\"dialCode\":\"221\",\"code\":\"SN\"},\n"
				+ "{\"name\":\"Serbia\",\"dialCode\":\"381\",\"code\":\"RS\"},\n"
				+ "{\"name\":\"Seychelles\",\"dialCode\":\"248\",\"code\":\"SC\"},\n"
				+ "{\"name\":\"Sierra Leone\",\"dialCode\":\"232\",\"code\":\"SL\"},\n"
				+ "{\"name\":\"Singapore\",\"dialCode\":\"65\",\"code\":\"SG\"},\n"
				+ "{\"name\":\"Sint Maarten\",\"dialCode\":\"1\",\"code\":\"SX\"},\n"
				+ "{\"name\":\"Slovakia\",\"dialCode\":\"421\",\"code\":\"SK\"},\n"
				+ "{\"name\":\"Slovenia\",\"dialCode\":\"386\",\"code\":\"SI\"},\n"
				+ "{\"name\":\"Solomon Islands\",\"dialCode\":\"677\",\"code\":\"SB\"},\n"
				+ "{\"name\":\"Somalia\",\"dialCode\":\"252\",\"code\":\"SO\"},\n"
				+ "{\"name\":\"South Africa\",\"dialCode\":\"27\",\"code\":\"ZA\"},\n"
				+ "{\"name\":\"South Korea\",\"dialCode\":\"82\",\"code\":\"KR\"},\n"
				+ "{\"name\":\"South Sudan\",\"dialCode\":\"211\",\"code\":\"SS\"},\n"
				+ "{\"name\":\"Spain\",\"dialCode\":\"34\",\"code\":\"ES\"},\n"
				+ "{\"name\":\"Sri Lanka\",\"dialCode\":\"94\",\"code\":\"LK\"},\n"
				+ "{\"name\":\"St. Lucia\",\"dialCode\":\"1\",\"code\":\"LC\"},\n"
				+ "{\"name\":\"Sudan\",\"dialCode\":\"249\",\"code\":\"SD\"},\n"
				+ "{\"name\":\"Suriname\",\"dialCode\":\"597\",\"code\":\"SR\"},\n"
				+ "{\"name\":\"Swaziland\",\"dialCode\":\"268\",\"code\":\"SZ\"},\n"
				+ "{\"name\":\"Sweden\",\"dialCode\":\"46\",\"code\":\"SE\"},\n"
				+ "{\"name\":\"Switzerland\",\"dialCode\":\"41\",\"code\":\"CH\"},\n"
				+ "{\"name\":\"Syria\",\"dialCode\":\"963\",\"code\":\"SY\"},\n"
				+ "{\"name\":\"Taiwan\",\"dialCode\":\"886\",\"code\":\"TW\"},\n"
				+ "{\"name\":\"Tajikistan\",\"dialCode\":\"992\",\"code\":\"TJ\"},\n"
				+ "{\"name\":\"Tanzania\",\"dialCode\":\"255\",\"code\":\"TZ\"},\n"
				+ "{\"name\":\"Thailand\",\"dialCode\":\"66\",\"code\":\"TH\"},\n"
				+ "{\"name\":\"The Bahamas\",\"dialCode\":\"1\",\"code\":\"BS\"},\n"
				+ "{\"name\":\"The Gambia\",\"dialCode\":\"220\",\"code\":\"GM\"},\n"
				+ "{\"name\":\"Timor-Leste\",\"dialCode\":\"670\",\"code\":\"TL\"},\n"
				+ "{\"name\":\"Togo\",\"dialCode\":\"228\",\"code\":\"TG\"},\n"
				+ "{\"name\":\"Tokelau\",\"dialCode\":\"690\",\"code\":\"TK\"},\n"
				+ "{\"name\":\"Tonga\",\"dialCode\":\"676\",\"code\":\"TO\"},\n"
				+ "{\"name\":\"Trinidad and Tobago\",\"dialCode\":\"1\",\"code\":\"TT\"},\n"
				+ "{\"name\":\"Tunisia\",\"dialCode\":\"216\",\"code\":\"TN\"},\n"
				+ "{\"name\":\"Turkey\",\"dialCode\":\"90\",\"code\":\"TR\"},\n"
				+ "{\"name\":\"Turkmenistan\",\"dialCode\":\"993\",\"code\":\"TM\"},\n"
				+ "{\"name\":\"Turks and Caicos Islands\",\"dialCode\":\"1\",\"code\":\"TC\"},\n"
				+ "{\"name\":\"Tuvalu\",\"dialCode\":\"688\",\"code\":\"TV\"},\n"
				+ "{\"name\":\"Uganda\",\"dialCode\":\"256\",\"code\":\"UG\"},\n"
				+ "{\"name\":\"Ukraine\",\"dialCode\":\"380\",\"code\":\"UA\"},\n"
				+ "{\"name\":\"United Arab Emirates\",\"dialCode\":\"971\",\"code\":\"AE\"},\n"
				+ "{\"name\":\"United Kingdom\",\"dialCode\":\"44\",\"code\":\"GB\"},\n"
				+ "{\"name\":\"United States\",\"dialCode\":\"1\",\"code\":\"US\"},\n"
				+ "{\"name\":\"Uruguay\",\"dialCode\":\"598\",\"code\":\"UY\"},\n"
				+ "{\"name\":\"US Virgin Islands\",\"dialCode\":\"1\",\"code\":\"VI\"},\n"
				+ "{\"name\":\"Uzbekistan\",\"dialCode\":\"998\",\"code\":\"UZ\"},\n"
				+ "{\"name\":\"Vanuatu\",\"dialCode\":\"678\",\"code\":\"VU\"},\n"
				+ "{\"name\":\"Venezuela\",\"dialCode\":\"58\",\"code\":\"VE\"},\n"
				+ "{\"name\":\"Vietnam\",\"dialCode\":\"84\",\"code\":\"VN\"},\n"
				+ "{\"name\":\"Wallis and Futuna\",\"dialCode\":\"681\",\"code\":\"WF\"},\n"
				+ "{\"name\":\"Western Sahara\",\"dialCode\":\"212\",\"code\":\"EH\"},\n"
				+ "{\"name\":\"Yemen\",\"dialCode\":\"967\",\"code\":\"YE\"},\n"
				+ "{\"name\":\"Zambia\",\"dialCode\":\"260\",\"code\":\"ZM\"}]";
		Country[] list = mapper.readValue(countryJson, Country[].class);
		for (Country country : list) {
			countryCodeCountryMap.put(country.getCode().toUpperCase(), country);
			countryNameCountryMap.put(country.getName().toUpperCase(), country);
			countryDialCodeCountryMap.put(country.getDialCode().toUpperCase(), country);
		}
	}

	public static Country getCountryByCode(String code) {
		return countryCodeCountryMap.get(code.toUpperCase());
	}

	public static Country getCountryByName(String name) {
		return countryNameCountryMap.get(name.toUpperCase());
	}

	public static Country getCountryByDialCode(String dialcode) {
		return countryDialCodeCountryMap.get(dialcode.toUpperCase());
	}
}
